apiVersion: v1
kind: ServiceAccount
metadata:
  name: istioctl-debug
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istioctl-readonly
rules:
- apiGroups: [""]
  resources: ["pods", "pods/logs","configmaps","secrets","services", "endpoints", "namespaces", "nodes","serviceaccounts/token","serviceaccounts"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
    - serviceaccounts/token
  verbs: ["create"]  # ✅ 新增這條，支援 istioctl 建立 token
- apiGroups: [""]
  resources:
    - pods/portforward
  verbs: ["create"]  # ✅ 新增：允許 istioctl 建立 port-forward 連線
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets","daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.istio.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["authentication.istio.io", "security.istio.io", "telemetry.istio.io", "extensions.istio.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["list", "watch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations","mutatingwebhookconfigurations"]
  verbs: ["list", "watch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gateways"]
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istioctl-debug-readonly-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istioctl-readonly
subjects:
- kind: ServiceAccount
  name: istioctl-debug
  namespace: default

