# istioctl-debug/deploy.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: istioctl-debug-1-24-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istioctl-debug
  template:
    metadata:
      labels:
        app: istioctl-debug
    spec:
      serviceAccountName: istioctl-debug
      containers:
      - name: istioctl
        image: istioctl-debug:1-24-0
        command: ["/bin/bash"]
        args: ["-c", "sleep infinity"]

